fixed bandit

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -69,13 +69,22 @@ jobs:
         #The default PostgreSQL port
       POSTGRES_PORT: 5432
         #New code starts here
+   
     - name: Run Bandit security scanner
-      run: bandit -r . -f sarif -o bandit-report.sarif
-            
+            run: bandit -r . -f sarif -o bandit-report.sarif || echo "BANDIT_FAIL=true" >> "$GITHUB_ENV"
+
     - name: Upload Bandit scan results to Github Code Scanning
-      uses: github/codeql-action/upload-sarif@v2
-      with:
-        sarif_file: bandit-report.sarif
+        uses: github/codeql-action/upload-sarif@v2
+            with:
+                  sarif_file: bandit-report.sarif
+
+    - name: Exit if Bandit fails
+        run: | 
+              if [ -n "$BANDIT_FAIL" ]; then
+                    exit 1 
+                        fi
+
+
 
 
   docker-build:
